# Generated by Django 5.1 on 2024-10-01 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(auto_created='False', primary_key='True', serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('biography', models.TextField(blank='True', null='True', verbose_name='Short Biography')),
                ('dob', models.TextField(blank='True', null='True', verbose_name='Date of Birth')),
            ],
        ),
    ]
