# Generated by Django 5.1 on 2024-10-01 15:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('blog', models.TextField(blank=True, null=True)),
                ('view_permission', models.CharField(choices=[('global', 'Global'), ('public', 'Public'), ('private', 'Private')], max_length=20)),
                ('author', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='authors.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
