# Generated by Django 5.1 on 2024-10-01 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.IntegerField(auto_created='False', primary_key='True', serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('reader', models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='readers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
