# Generated by Django 5.1 on 2024-10-01 15:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.TextField(verbose_name='Name of the Book')),
                ('genre', models.TextField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('view_permission', models.CharField(choices=[('global', 'Global'), ('public', 'Public'), ('private', 'Private')], max_length=20)),
                ('writer', models.ManyToManyField(blank='True', null='True', related_name='books', to='authors.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.TextField(blank=True, null=True, verbose_name='Chapter No. and Title')),
                ('book', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
